// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEKpKcK-7qowdjKv5t7PuxIi6iPf7RyM',
    appId: '1:282479979147:web:a0b5401c5f68f2c24d428e',
    messagingSenderId: '282479979147',
    projectId: 'psyagen-f459e',
    authDomain: 'psyagen-f459e.firebaseapp.com',
    storageBucket: 'psyagen-f459e.firebasestorage.app',
    measurementId: 'G-0K4NVHV9PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZokPxElTiP3FjqBrdYIkkfCQNH70u1kc',
    appId: '1:282479979147:android:f1d77805ae9952cf4d428e',
    messagingSenderId: '282479979147',
    projectId: 'psyagen-f459e',
    storageBucket: 'psyagen-f459e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTj1QGliHgZHqFnqH_UmyLUXgESzyqtw',
    appId: '1:282479979147:ios:231a14222eaad0834d428e',
    messagingSenderId: '282479979147',
    projectId: 'psyagen-f459e',
    storageBucket: 'psyagen-f459e.firebasestorage.app',
    iosBundleId: 'com.example.psyagend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTj1QGliHgZHqFnqH_UmyLUXgESzyqtw',
    appId: '1:282479979147:ios:231a14222eaad0834d428e',
    messagingSenderId: '282479979147',
    projectId: 'psyagen-f459e',
    storageBucket: 'psyagen-f459e.firebasestorage.app',
    iosBundleId: 'com.example.psyagend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkEKpKcK-7qowdjKv5t7PuxIi6iPf7RyM',
    appId: '1:282479979147:web:5608a22a01eadadd4d428e',
    messagingSenderId: '282479979147',
    projectId: 'psyagen-f459e',
    authDomain: 'psyagen-f459e.firebaseapp.com',
    storageBucket: 'psyagen-f459e.firebasestorage.app',
    measurementId: 'G-0FXXED3GW3',
  );

}